---
development:
  cloud_name: dmrxjjmxw
  api_key: '951888135828544'
  api_secret: FzjCROq1BYt4-5MlXiUPIEhQnbM
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: dmrxjjmxw
  api_key: '951888135828544'
  api_secret: FzjCROq1BYt4-5MlXiUPIEhQnbM
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: dmrxjjmxw
  api_key: '951888135828544'
  api_secret: FzjCROq1BYt4-5MlXiUPIEhQnbM
  enhance_image_tag: true
  static_image_support: false
